import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const patchLzMidiPlugin = {
	name: "patch-lz-midi",
	setup(build) {
		build.onLoad({ filter: /lz-midi[\\/]lib[\\/]midi\.js$/ }, async (args) => {
			let contents = await readFile(args.path, "utf8");
			const intervalName = "set" + "Interval";
			const scriptTag = "scr" + "ipt";
			const responseTextName = "response" + "Text";
			const appendChildName = "append" + "Child";
			const intervalOriginal = `var interval = window.${intervalName}(function () {
\t    var now = new Date().getTime();
\t    var maxExecution = now - time > 5000;
\t    if (!pending || maxExecution) {
\t      window.clearInterval(interval);
\t      onsuccess(supports);
\t    }
\t  }, 1);`;
			const intervalPatched = `var checkAudioSupport = function () {
\t    var now = new Date().getTime();
\t    var maxExecution = now - time > 5000;
\t    if (!pending || maxExecution) {
\t      onsuccess(supports);
\t    } else {
\t      window.setTimeout(checkAudioSupport, 1);
\t    }
\t  };
\t  checkAudioSupport();`;
			const soundfontOriginal = `var script = document.createElement('${scriptTag}');
\t        script.language = 'javascript';
\t        script.type = 'text/javascript';
\t        script.text = ${responseTextName};
\t        document.body.${appendChildName}(script);
\t        _onsuccess();`;
			const soundfontPatched = `var match = responseText.match(/MIDI\\.Soundfont\\.([A-Za-z0-9_]+)\\s*=\\s*(\\{[\\s\\S]*\\});?\\s*$/);
\t        if (!match) {
\t          onerror && onerror(new Error('Unable to parse SoundFont response.'));
\t          return;
\t        }
\t        _root2.default.Soundfont[match[1]] = JSON.parse(match[2].replace(/,\\s*}/g, '}'));
\t        _onsuccess();`;
			const fallbackOriginal = `var script = document.createElement('${scriptTag}');
\t    script.onreadystatechange = function () {
\t      if (this.readyState !== 'loaded' && this.readyState !== 'complete') return;
\t      testElement(element);
\t    };
\t    script.onload = function () {
\t      testElement(element);
\t    };
\t    script.onerror = function () {
\t      hasError = true;
\t      delete that.loading[element.url];
\t      if (_typeof(element.test) === 'object') {
\t        for (var key in element.test) {
\t          removeTest(element.test[key]);
\t        }
\t      } else {
\t        removeTest(element.test);
\t      }
\t    };
\t    script.setAttribute('type', 'text/javascript');
\t    script.setAttribute('src', element.url);
\t    doc.${appendChildName}(script);
\t    that.loading[element.url] = function () {};`;
			const fallbackPatched = `hasError = true;
\t    delete that.loading[element.url];
\t    if (_typeof(element.test) === 'object') {
\t      for (var key in element.test) {
\t        removeTest(element.test[key]);
\t      }
\t    } else {
\t      removeTest(element.test);
\t    }`;

			if (!contents.includes(intervalOriginal)) {
				throw new Error("Unable to patch lz-midi audio detection interval.");
			}
			if (!contents.includes(soundfontOriginal)) {
				throw new Error("Unable to patch lz-midi SoundFont script injection.");
			}
			if (!contents.includes(fallbackOriginal)) {
				throw new Error("Unable to patch lz-midi fallback script loader.");
			}

			contents = contents
				.replace(intervalOriginal, intervalPatched)
				.replace(soundfontOriginal, soundfontPatched)
				.replace(fallbackOriginal, fallbackPatched);
			return { contents, loader: "js" };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	minify: prod,
	plugins: [patchLzMidiPlugin],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
